name: .NET Build and Test
description: Builds, tests, and uploads test results for a .NET project
inputs:
  dotnet-version:
    description: The version of .NET SDK to use
    required: true
  test-results-path:
    description: Directory to store test results
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup dotnet ${{ inputs.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Display dotnet version
      run: dotnet --version
      shell: bash  

    - name: Install dependencies
      run: dotnet restore
      shell: bash 

    - name: Build
      run: dotnet build
      shell: bash  

    - name: Test with dotnet
      run: dotnet test --logger trx --results-directory "${{ inputs.test-results-path }}"
      shell: bash  

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ inputs.dotnet-version }}
        path: "${{ inputs.test-results-path }}"
      if: ${{ always() }}
