name: Push Docker Image to Docker Hub
description: Pushes a Docker image to Docker Hub
inputs:
  image-name:
    description: Name of the Docker image to push
    required: true
  docker-username:
    description: Docker Hub username
    required: true
  docker-password:
    description: Docker Hub password
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Push Docker image
      run: |
        docker push ${{ inputs.image-name }}
