services:
  englishnote.api:
    image: ${DOCKER_REGISTRY-}englishnoteapi
    build:
      context: .
      dockerfile: ../../Host/EnglishNote.Api/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=tcp:sql-server,1433;Database=EnglishNoteDb;User=sa;Password=EnglishNote@2023!;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;
    depends_on:
      - sql-server
    networks:
      - englishnote-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EnglishNote@2023!
    ports:
      - "1433:1433"  
    networks:
      - englishnote-network
    volumes:
      - sql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"  
    networks:
      - englishnote-network
    volumes:
      - azurite_data:/data

networks:
  englishnote-network:
    driver: bridge

volumes:
  sql-data:
    driver: local
  azurite_data:
    driver: local